/**
 * ManageSpace Payment API
 * ManageSpace Payment API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PaymentMethod } from './paymentMethod';

export class CreatePaymentTransaction {
    /**
    * The identifier of the shopping cart.
    */
    'cartId': string;
    /**
    * Amount in smallest currency unit (e.g. cents for USD).
    */
    'amount': number;
    'paymentMethod'?: PaymentMethod;
    /**
    * Account ID
    */
    'accountId': string;
    /**
    * Payment type
    */
    'paymentType'?: CreatePaymentTransaction.PaymentTypeEnum = CreatePaymentTransaction.PaymentTypeEnum.CreditCard;
    /**
    * Check number
    */
    'checkNumber'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "cartId",
            "baseName": "cartId",
            "type": "string"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "number"
        },
        {
            "name": "paymentMethod",
            "baseName": "paymentMethod",
            "type": "PaymentMethod"
        },
        {
            "name": "accountId",
            "baseName": "accountId",
            "type": "string"
        },
        {
            "name": "paymentType",
            "baseName": "paymentType",
            "type": "CreatePaymentTransaction.PaymentTypeEnum"
        },
        {
            "name": "checkNumber",
            "baseName": "checkNumber",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CreatePaymentTransaction.attributeTypeMap;
    }
}

export namespace CreatePaymentTransaction {
    export enum PaymentTypeEnum {
        CreditCard = <any> 'credit_card',
        Cash = <any> 'cash',
        Check = <any> 'check'
    }
}
