/**
 * ManageSpace Payment API
 * ManageSpace Payment API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PaymentTransactionRequestRequest } from './paymentTransactionRequestRequest';

export class PaymentTransactionRequest {
    'request': PaymentTransactionRequestRequest;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "request",
            "baseName": "request",
            "type": "PaymentTransactionRequestRequest"
        }    ];

    static getAttributeTypeMap() {
        return PaymentTransactionRequest.attributeTypeMap;
    }
}

