/**
 * ManageSpace Payment API
 * ManageSpace Payment API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PaymentTransactionResponsePaymentMethod } from './paymentTransactionResponsePaymentMethod';
import { PaymentTransactionStatus } from './paymentTransactionStatus';
import { PaymentTransactionTypeEnum } from './paymentTransactionTypeEnum';
import { TransactionTypeEnum } from './transactionTypeEnum';

export class PaymentTransactionResponse {
    /**
    * Payment Transaction ID.
    */
    'paymentTransactionId': string;
    /**
    * The identifier of the payment intent associated with the payment transaction.
    */
    'paymentProviderId': string;
    /**
    * Account id.
    */
    'accountId': string;
    /**
    * Account Name
    */
    'accountName': string;
    /**
    * Account Email Address
    */
    'email': string | null;
    /**
    * Account Mobile Number
    */
    'mobileNumber': string;
    /**
    * Site id.
    */
    'siteId': string;
    /**
    * Shopping cart id.
    */
    'cartId': string | null;
    /**
    * Amount in smallest currency unit (e.g. cents for USD).
    */
    'amount': number;
    'paymentTransactionStatus': PaymentTransactionStatus;
    'paymentTransactionType': PaymentTransactionTypeEnum;
    'transactionType': TransactionTypeEnum;
    'paymentMethod': PaymentTransactionResponsePaymentMethod | null;
    /**
    * Client secret for use with payment provider.
    */
    'clientSecret': string | null;
    /**
    * Created at.
    */
    'createdAt': string;
    /**
    * Created by.
    */
    'createdBy': string;
    /**
    * Invoice ID.
    */
    'invoiceId': string;
    /**
    * Created at.
    */
    'updatedAt': string | null;
    /**
    * Check number in case a payment transaction was check.
    */
    'reference': string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "paymentTransactionId",
            "baseName": "paymentTransactionId",
            "type": "string"
        },
        {
            "name": "paymentProviderId",
            "baseName": "paymentProviderId",
            "type": "string"
        },
        {
            "name": "accountId",
            "baseName": "accountId",
            "type": "string"
        },
        {
            "name": "accountName",
            "baseName": "accountName",
            "type": "string"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "mobileNumber",
            "baseName": "mobileNumber",
            "type": "string"
        },
        {
            "name": "siteId",
            "baseName": "siteId",
            "type": "string"
        },
        {
            "name": "cartId",
            "baseName": "cartId",
            "type": "string"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "number"
        },
        {
            "name": "paymentTransactionStatus",
            "baseName": "paymentTransactionStatus",
            "type": "PaymentTransactionStatus"
        },
        {
            "name": "paymentTransactionType",
            "baseName": "paymentTransactionType",
            "type": "PaymentTransactionTypeEnum"
        },
        {
            "name": "transactionType",
            "baseName": "transactionType",
            "type": "TransactionTypeEnum"
        },
        {
            "name": "paymentMethod",
            "baseName": "paymentMethod",
            "type": "PaymentTransactionResponsePaymentMethod"
        },
        {
            "name": "clientSecret",
            "baseName": "clientSecret",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "string"
        },
        {
            "name": "createdBy",
            "baseName": "createdBy",
            "type": "string"
        },
        {
            "name": "invoiceId",
            "baseName": "invoiceId",
            "type": "string"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "string"
        },
        {
            "name": "reference",
            "baseName": "reference",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return PaymentTransactionResponse.attributeTypeMap;
    }
}

export namespace PaymentTransactionResponse {
}
