/**
 * ManageSpace Payment API
 * ManageSpace Payment API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export enum PaymentTransactionStatus {
    Canceled = <any> 'canceled',
    Processing = <any> 'processing',
    RequiresAction = <any> 'requires_action',
    RequiresCapture = <any> 'requires_capture',
    RequiresConfirmation = <any> 'requires_confirmation',
    RequiresPaymentMethod = <any> 'requires_payment_method',
    Succeeded = <any> 'succeeded',
    Failed = <any> 'failed'
}
