/**
 * ManageSpace Payment API
 * ManageSpace Payment API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export enum TransactionStatusCodeNames {
    InProgress = <any> 'IN_PROGRESS',
    Success = <any> 'SUCCESS',
    Failed = <any> 'FAILED',
    Incomplete = <any> 'INCOMPLETE'
}
