/**
 * ManageSpace Payment API
 * ManageSpace Payment API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PaymentTransactionResponsePaymentMethod } from './paymentTransactionResponsePaymentMethod';
import { TransactionStatusResponse } from './transactionStatusResponse';

export class TransactionResponse {
    /**
    * Transaction ID.
    */
    'transactionId': string;
    /**
    * The subscription ID of the payment intent associated with the transaction.
    */
    'subscriptionId': string;
    /**
    * The invoice ID of the payment intent
    */
    'invoiceId': string;
    /**
    * Account id.
    */
    'accountId': string;
    /**
    * Account Name
    */
    'accountName': string;
    /**
    * Account Email Address
    */
    'email': string | null;
    /**
    * Account Mobile Number
    */
    'mobileNumber': string;
    /**
    * Site id.
    */
    'siteId': string;
    /**
    * Lease id.
    */
    'leaseId': string | null;
    /**
    * Unit id.
    */
    'unitId': string;
    /**
    * Shopping cart id.
    */
    'shoppingCartId': string;
    /**
    * The currency.
    */
    'currency': string;
    /**
    * Amount in smallest currency unit (e.g. cents for USD).
    */
    'amount': number;
    'status': TransactionStatusResponse;
    'paymentMethod': PaymentTransactionResponsePaymentMethod | null;
    /**
    * Created at.
    */
    'createdAt': string;
    /**
    * Created at.
    */
    'updatedAt': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "transactionId",
            "baseName": "transactionId",
            "type": "string"
        },
        {
            "name": "subscriptionId",
            "baseName": "subscriptionId",
            "type": "string"
        },
        {
            "name": "invoiceId",
            "baseName": "invoiceId",
            "type": "string"
        },
        {
            "name": "accountId",
            "baseName": "accountId",
            "type": "string"
        },
        {
            "name": "accountName",
            "baseName": "accountName",
            "type": "string"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "mobileNumber",
            "baseName": "mobileNumber",
            "type": "string"
        },
        {
            "name": "siteId",
            "baseName": "siteId",
            "type": "string"
        },
        {
            "name": "leaseId",
            "baseName": "leaseId",
            "type": "string"
        },
        {
            "name": "unitId",
            "baseName": "unitId",
            "type": "string"
        },
        {
            "name": "shoppingCartId",
            "baseName": "shoppingCartId",
            "type": "string"
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "number"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "TransactionStatusResponse"
        },
        {
            "name": "paymentMethod",
            "baseName": "paymentMethod",
            "type": "PaymentTransactionResponsePaymentMethod"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "string"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return TransactionResponse.attributeTypeMap;
    }
}

