/**
 * ManageSpace Payment API
 * ManageSpace Payment API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { TransactionStatusCodeNames } from './transactionStatusCodeNames';

export class TransactionStatusResponse {
    /**
    * Transaction Status Id
    */
    'transactionStatusId': number;
    'codeName': TransactionStatusCodeNames;
    /**
    * Display Name
    */
    'displayName': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "transactionStatusId",
            "baseName": "transactionStatusId",
            "type": "number"
        },
        {
            "name": "codeName",
            "baseName": "codeName",
            "type": "TransactionStatusCodeNames"
        },
        {
            "name": "displayName",
            "baseName": "displayName",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return TransactionStatusResponse.attributeTypeMap;
    }
}

export namespace TransactionStatusResponse {
}
